sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "vA6TXDIxeFzvZMOr/gZX8T2hd/cGIoloyxKYcPmATVZxxZeUFAPDMCvFBryfiR0u29orn4RShgRfBgFh8f+LW58ZnZFBAOaDE5NXZpM+267LE4N8MlZwnldGK6tNkTCpRbceC3DC+NNIGksAfofpzFPw1aP7drEEHGHFyRV0MT9cr+nrr+eX4zhfyMW9oE/429UHiKX4SoDBhnG2cOBlelBaVaBU0z1BKxjusA5lI963cM7laHGxPRcZNAwlqiekKTCCpq+xcI1AeNhw1l55i+sITpgaFVId11q2Mw8rRCpHsg09BHdEEg4efhewAmae0j1MBH53iqsZ9YETfoz9UGfrNpN/Zgv2GDgn850MZ5W2ekElrJ5UUhLZpC2RiaoUa0Zxr9eXRtBg4ZDRCKODOLInDRkO2FmehpSIp2F4J1qLDGI2d6CNoZTkfsnrXXdCEqImFaK5DkuJSqB4GVqK+NeMRjVJcmUeXsIFgZo+CUJtHeAl2u5ZBFhxV5G5dfwva7eMjt/6fx13z6MQQisS2oTkxamJ1mglj4nwZbF7Q6gwAh8qIsgyx3YdbUuDh2i14FuF7y4r4W/nkgolv2F3OvL8FfsUoOkxfTdBnW8164l3vEbNozVdWnOCKc/SqkHM5ibJ5od/Cf6cdTyiP/lerEKzNOX0XtEoABSAXar7el0="
  - secure: "YdHy6vJEUOe2FKn5tNzqtW9JrscF3ss2BtJZae1GnHkENC/aUVQmsTzxPkIdVdnuWOE+tAq3gsKcCaCNElicYYudHo6xudTEQg4ERDce0DCrLI5hBaTMaMFn5LmfAsfU+Xfmm1UkwGBZ3G9d6pQHsIr1bVlDXNvYaLvVFCCAPhuUXN9xq+TXGvifl8v7YqAohelOXPWhhKNZcZ8Q6F1zdDqE9/SiiC2Dii+HQjuMU79zoc2tej9fpG9ayf3ayHbpIeyerZVbYdHD7BisMExmT9uhcfCcG5XnCvnhgHLvn8ewBHqSsyr/NN18i8eb8p/sl9ec4qNMgkooQu2V8S1TN8hsmwrMPqX3yr96ENENv5EO1HyZs/CgUpI6Jau+m5Yt7bJa5cLOiROIrcjcWgm3mwxGAEmOG5e2e37A9wZZOq2OZa1o/eyQ8eJaFvBCMU9bDGkVF9uM26mYzn2L78Te0PJ2faPFdWBbi1y19hhzAjRqueDyvkmhN/RFZ2Rixw/MvurvIqZ+UV4s5npGJhKZIZNMSZ7bEyicS4a80H00S0EVu/6wE5dlDqlUbZn1YovPlCqMZwqQ52+fxOkiS3Knf0UpcF69IlhtF6ypQkAi/7SMNyyE2Dj/DTt9Tp5Ja7w41Ps94UaeSeRdb7D0q+RwoAQenzvIRUd87T52M3FX5D4="
  - secure: "ByX1aIccGDwpOtVcEQ+2lsn5hciwB+IoBGxRXebM9pDkV/1qixnjD0b/gU58EcA//Cku0rhubLh329+uxQp1vzfUTkmZjLRglJCCnaBngPlj3pQ6thBNoVcOc9m0beEqTKRyo8XP4iH3wnLbBXW6yHtzC1WEJL8pK5TWBopUOAwGxKpog2xhIw00jSwrQc2z08SheMu+AGaQPUGLXb5ZJ4IaZGm01QvHPbE+8EFEShV2MKOoPcIcvjFbkasR4X9QiRdh6H2uKOdmCY6Ey1xXaBHeAGr112LnqmHqIotp5uVt5c3YjHiz6JGmGmVPHyYSgzosT+OEfEv3Of9fkOFQXVsvH4/n1WOtf5j7IF6Sh9+KFMUeFD4Elzdqe6Cg8q+DOmDj45GRGfGfeJerOwthsGp+KJnl2dXqybBpp6jDDM/4c4OHTdpO9cHCJoxkT/P13D/xlns9WVRtP5uHbJ8Otu2n44htJ24t2cYYgEUN9tX2ahjMu7esOk8sTSYMWYf3kOrk6apRwyRIQg1VtGqP02KKbet/IVlzpbCSyR3jDtNDlhva7OJiebWJ8liFNWnELdhjLb5XqKz5Z+pKQUSIrwaAnUIqnWu/bGPGVetx06v0D0I1TVfR5uPpj4r0WNXEeL/MlqCfWMMHuAMDP13go5KK7Mkuz4q0SgzDmFSnvOs="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
